# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Package & Run Tests

on:
  push:
  pull_request:
    branches:
      - develop
      - master

env:
  2CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
  ACC_ID: ${{ secrets.ACC_ID }}
  ACC_PASS: ${{ secrets.ACC_PASS }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
